name: Test

on:
  workflow_dispatch:
    inputs:
      dry:
        type: boolean
        description: dry
        default: true
jobs:
  deploy:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - name: Pull $image
      run: |
        env
      env:
        DRY: ${{ github.event.inputs.dry }}
        IS_DEFAULT: ${{ inputs.github.ref != format('refs/heads/{0}', github.event.repository.default_branch ) }}
        RESULT: ${{ github.event.inputs.dry || inputs.github.ref != format('refs/heads/{0}', github.event.repository.default_branch ) }}
